# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shikatsu/repos/rt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shikatsu/repos/rt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shikatsu/repos/rt/CMakeFiles /home/shikatsu/repos/rt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shikatsu/repos/rt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rt

# Build rule for target.
rt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rt
.PHONY : rt

# fast build rule for target.
rt/fast:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/build
.PHONY : rt/fast

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/CameraRay.o: src/CameraRay.cpp.o
.PHONY : src/CameraRay.o

# target to build an object file
src/CameraRay.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/CameraRay.cpp.o
.PHONY : src/CameraRay.cpp.o

src/CameraRay.i: src/CameraRay.cpp.i
.PHONY : src/CameraRay.i

# target to preprocess a source file
src/CameraRay.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/CameraRay.cpp.i
.PHONY : src/CameraRay.cpp.i

src/CameraRay.s: src/CameraRay.cpp.s
.PHONY : src/CameraRay.s

# target to generate assembly for a file
src/CameraRay.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/CameraRay.cpp.s
.PHONY : src/CameraRay.cpp.s

src/Color.o: src/Color.cpp.o
.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i
.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s
.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/ColorTexture.o: src/ColorTexture.cpp.o
.PHONY : src/ColorTexture.o

# target to build an object file
src/ColorTexture.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/ColorTexture.cpp.o
.PHONY : src/ColorTexture.cpp.o

src/ColorTexture.i: src/ColorTexture.cpp.i
.PHONY : src/ColorTexture.i

# target to preprocess a source file
src/ColorTexture.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/ColorTexture.cpp.i
.PHONY : src/ColorTexture.cpp.i

src/ColorTexture.s: src/ColorTexture.cpp.s
.PHONY : src/ColorTexture.s

# target to generate assembly for a file
src/ColorTexture.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/ColorTexture.cpp.s
.PHONY : src/ColorTexture.cpp.s

src/DamierTexture.o: src/DamierTexture.cpp.o
.PHONY : src/DamierTexture.o

# target to build an object file
src/DamierTexture.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/DamierTexture.cpp.o
.PHONY : src/DamierTexture.cpp.o

src/DamierTexture.i: src/DamierTexture.cpp.i
.PHONY : src/DamierTexture.i

# target to preprocess a source file
src/DamierTexture.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/DamierTexture.cpp.i
.PHONY : src/DamierTexture.cpp.i

src/DamierTexture.s: src/DamierTexture.cpp.s
.PHONY : src/DamierTexture.s

# target to generate assembly for a file
src/DamierTexture.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/DamierTexture.cpp.s
.PHONY : src/DamierTexture.cpp.s

src/Exceptions.o: src/Exceptions.cpp.o
.PHONY : src/Exceptions.o

# target to build an object file
src/Exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Exceptions.cpp.o
.PHONY : src/Exceptions.cpp.o

src/Exceptions.i: src/Exceptions.cpp.i
.PHONY : src/Exceptions.i

# target to preprocess a source file
src/Exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Exceptions.cpp.i
.PHONY : src/Exceptions.cpp.i

src/Exceptions.s: src/Exceptions.cpp.s
.PHONY : src/Exceptions.s

# target to generate assembly for a file
src/Exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Exceptions.cpp.s
.PHONY : src/Exceptions.cpp.s

src/Intersection.o: src/Intersection.cpp.o
.PHONY : src/Intersection.o

# target to build an object file
src/Intersection.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Intersection.cpp.o
.PHONY : src/Intersection.cpp.o

src/Intersection.i: src/Intersection.cpp.i
.PHONY : src/Intersection.i

# target to preprocess a source file
src/Intersection.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Intersection.cpp.i
.PHONY : src/Intersection.cpp.i

src/Intersection.s: src/Intersection.cpp.s
.PHONY : src/Intersection.s

# target to generate assembly for a file
src/Intersection.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Intersection.cpp.s
.PHONY : src/Intersection.cpp.s

src/Light.o: src/Light.cpp.o
.PHONY : src/Light.o

# target to build an object file
src/Light.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Light.cpp.o
.PHONY : src/Light.cpp.o

src/Light.i: src/Light.cpp.i
.PHONY : src/Light.i

# target to preprocess a source file
src/Light.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Light.cpp.i
.PHONY : src/Light.cpp.i

src/Light.s: src/Light.cpp.s
.PHONY : src/Light.s

# target to generate assembly for a file
src/Light.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Light.cpp.s
.PHONY : src/Light.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Object.o: src/Object.cpp.o
.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i
.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s
.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Plane.o: src/Plane.cpp.o
.PHONY : src/Plane.o

# target to build an object file
src/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Plane.cpp.o
.PHONY : src/Plane.cpp.o

src/Plane.i: src/Plane.cpp.i
.PHONY : src/Plane.i

# target to preprocess a source file
src/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Plane.cpp.i
.PHONY : src/Plane.cpp.i

src/Plane.s: src/Plane.cpp.s
.PHONY : src/Plane.s

# target to generate assembly for a file
src/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Plane.cpp.s
.PHONY : src/Plane.cpp.s

src/PointLight.o: src/PointLight.cpp.o
.PHONY : src/PointLight.o

# target to build an object file
src/PointLight.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/PointLight.cpp.o
.PHONY : src/PointLight.cpp.o

src/PointLight.i: src/PointLight.cpp.i
.PHONY : src/PointLight.i

# target to preprocess a source file
src/PointLight.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/PointLight.cpp.i
.PHONY : src/PointLight.cpp.i

src/PointLight.s: src/PointLight.cpp.s
.PHONY : src/PointLight.s

# target to generate assembly for a file
src/PointLight.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/PointLight.cpp.s
.PHONY : src/PointLight.cpp.s

src/Ray.o: src/Ray.cpp.o
.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i
.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s
.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/RotMatrix.o: src/RotMatrix.cpp.o
.PHONY : src/RotMatrix.o

# target to build an object file
src/RotMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/RotMatrix.cpp.o
.PHONY : src/RotMatrix.cpp.o

src/RotMatrix.i: src/RotMatrix.cpp.i
.PHONY : src/RotMatrix.i

# target to preprocess a source file
src/RotMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/RotMatrix.cpp.i
.PHONY : src/RotMatrix.cpp.i

src/RotMatrix.s: src/RotMatrix.cpp.s
.PHONY : src/RotMatrix.s

# target to generate assembly for a file
src/RotMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/RotMatrix.cpp.s
.PHONY : src/RotMatrix.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Solver1.o: src/Solver1.cpp.o
.PHONY : src/Solver1.o

# target to build an object file
src/Solver1.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Solver1.cpp.o
.PHONY : src/Solver1.cpp.o

src/Solver1.i: src/Solver1.cpp.i
.PHONY : src/Solver1.i

# target to preprocess a source file
src/Solver1.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Solver1.cpp.i
.PHONY : src/Solver1.cpp.i

src/Solver1.s: src/Solver1.cpp.s
.PHONY : src/Solver1.s

# target to generate assembly for a file
src/Solver1.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Solver1.cpp.s
.PHONY : src/Solver1.cpp.s

src/Solver2.o: src/Solver2.cpp.o
.PHONY : src/Solver2.o

# target to build an object file
src/Solver2.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Solver2.cpp.o
.PHONY : src/Solver2.cpp.o

src/Solver2.i: src/Solver2.cpp.i
.PHONY : src/Solver2.i

# target to preprocess a source file
src/Solver2.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Solver2.cpp.i
.PHONY : src/Solver2.cpp.i

src/Solver2.s: src/Solver2.cpp.s
.PHONY : src/Solver2.s

# target to generate assembly for a file
src/Solver2.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Solver2.cpp.s
.PHONY : src/Solver2.cpp.s

src/Sphere.o: src/Sphere.cpp.o
.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i
.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s
.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/TypesInit.o: src/TypesInit.cpp.o
.PHONY : src/TypesInit.o

# target to build an object file
src/TypesInit.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/TypesInit.cpp.o
.PHONY : src/TypesInit.cpp.o

src/TypesInit.i: src/TypesInit.cpp.i
.PHONY : src/TypesInit.i

# target to preprocess a source file
src/TypesInit.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/TypesInit.cpp.i
.PHONY : src/TypesInit.cpp.i

src/TypesInit.s: src/TypesInit.cpp.s
.PHONY : src/TypesInit.s

# target to generate assembly for a file
src/TypesInit.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/TypesInit.cpp.s
.PHONY : src/TypesInit.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rt"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/CameraRay.o"
	@echo "... src/CameraRay.i"
	@echo "... src/CameraRay.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/ColorTexture.o"
	@echo "... src/ColorTexture.i"
	@echo "... src/ColorTexture.s"
	@echo "... src/DamierTexture.o"
	@echo "... src/DamierTexture.i"
	@echo "... src/DamierTexture.s"
	@echo "... src/Exceptions.o"
	@echo "... src/Exceptions.i"
	@echo "... src/Exceptions.s"
	@echo "... src/Intersection.o"
	@echo "... src/Intersection.i"
	@echo "... src/Intersection.s"
	@echo "... src/Light.o"
	@echo "... src/Light.i"
	@echo "... src/Light.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Plane.o"
	@echo "... src/Plane.i"
	@echo "... src/Plane.s"
	@echo "... src/PointLight.o"
	@echo "... src/PointLight.i"
	@echo "... src/PointLight.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/RotMatrix.o"
	@echo "... src/RotMatrix.i"
	@echo "... src/RotMatrix.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Solver1.o"
	@echo "... src/Solver1.i"
	@echo "... src/Solver1.s"
	@echo "... src/Solver2.o"
	@echo "... src/Solver2.i"
	@echo "... src/Solver2.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/TypesInit.o"
	@echo "... src/TypesInit.i"
	@echo "... src/TypesInit.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

